name: production

# 执行 CI 的时机: 当 git push 到 master 分支时
on:
  push:
    branches:    
      - main

# 执行所有的 jobs
jobs:
  deploy:
    # 该 Job 在自建的 Runner 中执行
    runs-on: self-hosted
    environment:
      # 获取 CICD 中的变量: Context
      # https://docs.github.com/en/actions/learn-github-actions/expressions
      name: deploy
      url: http://net.swttws.top
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
      - name: deploy
        run: docker-compose -f net.docker-compose.yaml up --build -d net
        env:
          COMMIT_REF_NAME: ${{ github.ref_name }}
